name: cpp-linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'  # Uses your .clang-format file
          tidy-checks: '' # Uses your .clang-tidy file
      - name: Fail if linter found errors
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
