name: cpp-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  cpp-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build

    - name: Run tests with CTest
      run: |
        cd build
        ctest --output-on-failure
